### ISSUE TITLE
Maintainer position

### ISSUE THREAD

**Issue by bereketsemagn** [coderjojo/creative-profile-readme#109]
Hey @coderjojo, will you be needing a maintainer for creative-profile-readme?
I can help out, if you'd like. I'm active everyday.

**Comment by coderjojo** [comment]
> Hey @coderjojo, will you be needing a maintainer for creative-profile-readme?
> I can help out, if you'd like. I'm active everyday.

As this repo is not that difficult to maintain I don't think it requires any additional new maintainer and even I'm quite active nowadays. Additionally, if you want to get into open source you can visit [this](https://github.com/up-for-grabs/up-for-grabs.net) website.

**Comment by bereketsemagn** [comment]
Sounds good @coderjojo, followed you on GitHub, you seem like a very sharp-minded person.
