### ISSUE TITLE
Having [ImgBot] on the repository to compress the screenshots uploaded

### ISSUE THREAD

**Issue by vishwasnavadak** [coderjojo/creative-profile-readme#31]
I have been using https://imgbot.net/ for automatically compressing the images that are added to my GitHub Repository. Wondering if you want to have it in this repository since lot of people are uploading screenshots. 

*Note:* I am no affiliated to the tool in any way, thought of suggesting it since I have found it very useful.

**Comment by coderjojo** [comment]
ImgBot is already active on this repository.
