### ISSUE TITLE
Hey Checkout our  Readme.md

### ISSUE THREAD

**Issue by johnmelodyme** [coderjojo/creative-profile-readme#383]
### Discussed in https://github.com/coderjojo/creative-profile-readme/discussions/363

<div type='discussions-op-text'>

<sup>Originally posted by **ritik2629** November 14, 2021</sup>

https://github.com/ritik2629 and 
https://github.com/johnmelodyme

Hope you like it</div>

**Comment by coderjojo** [comment]
You can do a pull request to add your profile.
