### ISSUE TITLE
Optimize images with lossy format

### ISSUE THREAD

**Issue by FMGordillo** [coderjojo/creative-profile-readme#447]
# Observable behavior

- Load time is 23 seconds
- Images are PNG (loseless)
- All page took 48MB
- [There is a Bot which does the optimization already](https://github.com/coderjojo/creative-profile-readme/pull/443), but it might not be enough

# Screenshot
<img width="458" alt="image" src="https://user-images.githubusercontent.com/7970174/183136804-2e9c0e80-b2b6-40f6-81ce-4b961574535f.png">

# Suggestions

- Transform them to `.webp` or other format [lossy](https://en.wikipedia.org/wiki/Lossy_compression)

**Comment by coderjojo** [comment]
Yes, Images are taking too much bandwidth and I guess [ImgBot](https://imgbot.net/) is not enough to compress those images.
Any quick method you know, we can do to convert/compress those images and also change the entries on readme section?

**Comment by FMGordillo** [comment]
I can submit a PR to convert those images and their corresponding links in the README, wait for me on that 

In the meantime, ImgBot can optimize wepb files?

**Comment by coderjojo** [comment]
If ImgBot didn't work then [image-actions](https://github.com/calibreapp/image-actions) can be used.
