### ISSUE TITLE
Add screenshots of the result for each contribution

### ISSUE THREAD

**Issue by Israel-Laguan** [coderjojo/creative-profile-readme#5]
# Rationale

When you enter this project is very likely you are searching for ideas. Maybe you had some doubts about what to add, what is allowed, and wish to see some cool tricks to use on your own version. Os it's paramount to have a look into each contribution and judge if something from that contribution is useful.

In the current form, the one searching for ideas has to enter **each repository** and then ponder if is useful. Then enter the RAW version of the README.md and read/take.

## Proposal

To avoid one step, to see if ideas are useful, I propose to ask a small screenshot of the result. This will optimize time for the people using this project by avoiding to open each and all the repositories. For people in counties with internet constraints, or when a tight schedule makes it impossible to waste too much time, the proposal is valid.

#### Benefits

- Faster to get what you are searching for.
- You can easily compare options
- Fewer resources and time wasted.

### Drawbacks

- Each repository has fewer visits.
- It can force to focus on the final looks instead of the functionality, in order to be "the best", leading to unnecessary competency.

## Proposed format for contribution

- `[Name](Link)`

`[Screnshot, max 640 height, can be PNG or JP(E)G]`

GIFs can be too much for some people with low bandwidth (or navigating from phone), also if the height is too large it can cover all the viewport and being unrespectful of other profiles.

Also the `[Name]` should be the GitHub's Profile and the `(Link)` GitHub's Profile URL, to see the final result. 

Lastly, the Maintainer should care when merging a PR if the screenshot shows any image or text promoting real, psychological, or simulated violence against any individual or group. If any profile is found violating this should be removed.

For example:

- [coderjojo](https://github.com/coderjojo)

![image](https://user-images.githubusercontent.com/36519478/87257384-2d0db900-c460-11ea-89ba-e259aa04409b.png)

**Comment by coderjojo** [comment]
This looks good. Adding images will be more useful for other's. Should we add images in a different section as adding in same README will make it hard to browse all the profiles?

**Comment by Israel-Laguan** [comment]
> Should we add images in a different section as adding in same README will make it hard to browse all the profiles?

You are right, maybe a separate `EXAMPLES.md` or `PREVIEW.md`, and a link in `README.md` with a text like "If you want to check a preview of each profile, visit **here**".

What do you think, or have any suggestions? Also thanks for taking my request into account!

**Comment by coderjojo** [comment]
Or we can have separate folder  `EXAMPLES` which will contain all `README.md ` with their respective name. Both options sounds good to me.

**Comment by Israel-Laguan** [comment]
Hmmm what about using `<details>` tag? The screenshot will only be visible when the visitor wants. That way we keep the README simple and complete at the same time

**Comment by coderjojo** [comment]
`<details>` tag will work pretty good.

**Comment by Israel-Laguan** [comment]
I will do this work in the next PR!

**Comment by Israel-Laguan** [comment]
#19 solves this issue, please check and close (or make changes if needed)
